Remove the version from the reference to SIL.LCModel.Core
The project shouldn't reference a specific version.  This is
to fix the following error:

D:\fwrepo\fw\Src\FXT\FxtDll\FxtDllTests\DumperTests.cs(34,23): error CS0012: The type 'ILgWritingSystemFactory' is defined in an assembly that is not referenced. You must add a reference to assembly 'SIL.LCModel.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=f245775b81dcfaab'. [D:\fwrepo\fw\Src\FXT\FxtDll\FxtDllTests\FxtDllTests.csproj]

Change-Id: I49060ac9e9009b808fcc73d618240f31bfa3aeda