Ignore deprecated-declarations warnings about pango
* g++ 9 is complaining about using deprecated functions:

  lib/VwGraphicsCairo.cpp(1461,47): error G8B87D070:
  'FT_FaceRec_* pango_fc_font_lock_face(PangoFcFont*)' is deprecated:
  Use 'pango_font_get_hb_font' instead
  [-Werror=deprecated-declarations]

  lib/VwGraphicsCairo.cpp(1465,32): error GEEA84499:
  'void pango_fc_font_unlock_face(PangoFcFont*)' is deprecated:
  Use 'pango_font_get_hb_font' instead
  [-Werror=deprecated-declarations]

* Ubuntu 20.04 introduces libpango-1.0-0 version 1.44.
* https://developer.gnome.org/pango/stable/PangoFcFont.html says
  "pango_fc_font_lock_face has been deprecated since version 1.44 and
  should not be used in newly-written code. Use
  pango_font_get_hb_font() instead", which was introduced in version
  1.44.
* For now ignore the deprecation warning. This may be simpler to
  resolve once all our supported Ubuntu releases have pango >= 1.44.

Change-Id: I2a180061d5bf0c9e4e5146e336d0ebd9b811aa03